---
title: "Iris SVM"
output: html_notebook
---

Using SVMs on the Iris Dataset.

```{r}
# Libraries
library(e1071)
```

```{r}
data(iris)
data <- iris
plot(data, col = iris$Species, pch = 19)
legend("topright", legend = levels(iris$Species), col = 1:3, pch = 19)
```

## One dimension
```{r}
# Subset and prepare the data
data <- iris[iris$Species %in% c("setosa", "virginica"), ]

# Fit the SVM model
model <- svm(Species ~ Petal.Width, data = data, kernel = "linear")

# Generate a sequence of Petal.Width values for prediction
Petal_width_range <- seq(
  min(data$Petal.Width),
  max(data$Petal.Width),
  length.out = 300
)

# Predict species for each value in Petal_width_range
predictions <- predict(
    model, data.frame(Petal.Width = Petal_width_range),
    decision.values = TRUE
)

# Extract decision values
dec_values <- attributes(predictions)$decision.values

# Find the Petal.Width value where decision value is closest to zero
boundary_point <- Petal_width_range[which.min(abs(dec_values))]

# Plotting
xlim <- c(0, 4)
ylim <- c(0, 1)
col <- c("red", "yellow", "blue")
plot(NA, xlim = xlim, ylim = ylim, axes = FALSE, ann = FALSE)
points(data$Petal.Width,
    rep(0, length(data$Petal.Width)),
    col = col[data$Species],
    pch = 19
)

axis(1)
axis(2, at = 0, labels = "Petal.Width")
title("iris Petal width")
points(boundary_point, 0, col = "green", pch = 4) # Mark the boundary point
legend("topleft", legend = c("setosa", "virginica"), col = c("red", "blue"), pch = 19)

```
## Two Dimensions


```{r}
data <- iris

# Fit SVM for two features
# Also supports linear, polynomial, radial, sigmoid
model <- svm(Species ~ Petal.Length + Petal.Width,
    data = data, kernel = "sigmoid", scale=FALSE
)

print(model)

# Tune the model
costs <- c(0.001,0.01,.1,1,10,100)
gammas <- c(0.1, 1, 10)
tuned_model <- tune(
    svm, Species ~ Petal.Length + Petal.Width,
    data = data, kernel = "linear",
    ranges = list(cost = costs, gamma = gammas)
)

print(tuned_model)

# Create a sequence of values for each dimension
sl <- seq(min(data$Petal.Length), max(data$Petal.Length), length = 100)
sw <- seq(min(data$Petal.Width), max(data$Petal.Width), length = 100)

# Expand grid to cover all combinations
grid <- expand.grid(Petal.Length = sl, Petal.Width = sw)

# Predict using the SVM model
grid$Species <- predict(model, grid)

# Plot
p <- ggplot(data, aes(x = Petal.Length, y = Petal.Width, color = Species)) +
    geom_point(alpha = 0.5, size = 3) +
    geom_tile(data = grid, aes(fill = Species, alpha = 2), color = NA) +
    scale_fill_manual(values = c("setosa" = "red", "virginica" = "blue", "versicolor" = "green")) +
    scale_color_manual(values = c("setosa" = "red", "virginica" = "blue", "versicolor" = "green")) +
    ggtitle("SVM Decision Boundary with Petal Measurements") +
    theme_minimal() +
    theme(legend.position = "top")

print(p)

# Confusion matrix on predictions
confusion_matrix <- table(data$Species, predict(model, data))
print(confusion_matrix)
```
